### ISSUE TITLE
Review section 5.5

### ISSUE THREAD

**Issue by guimou** [rh-aiservices-bu/insurance-claim-processing#117]
- How to properly apply the YAML?
- Update Doc
- Pipeline failing

**Comment by erwangranger** [comment]
my env shut down seconds before I could test this. 

the custom images in quay were not public and that was the reason my first pipeline had failed (imagepullbackoff). I wonder if this might be the cause of this issue too.

**Comment by guimou** [comment]
Fixed in #125
