### ISSUE TITLE
disclaimers

### ISSUE THREAD

**Issue by erwangranger** [rh-aiservices-bu/insurance-claim-processing#118]
since there are no built-in safeguards beyond the ones built into the prompt, it's easy to get the LLM to say very offensive things. (unlike chatGPT, for example). 
Should we warn the users, and have a legal disclaimers that with or without modification of the prompt, we can't be held responsible for what mistral will spit out? 

also. don't go sell an insurance solution. 
This is not "what's in openshift AI". This "what a customer could build with openShift AI".

**Comment by guimou** [comment]
Fixed in #123
