### ISSUE TITLE
Images mismatch in claim webapp

### ISSUE THREAD

**Issue by adrien-legros** [rh-aiservices-bu/insurance-claim-processing#122]
Images are not the same on the RHS and and the original claim content.

Screenshots:
![Screenshot from 2024-01-15 15-45-16](https://github.com/rh-aiservices-bu/insurance-claim-processing/assets/90031367/9ca2e00e-bde1-480f-9a34-6ce0f0e13b06)
![Screenshot from 2024-01-15 15-45-30](https://github.com/rh-aiservices-bu/insurance-claim-processing/assets/90031367/1236a26c-f63b-4f19-8381-9456f9174fa6)

**Comment by guimou** [comment]
Fixed in #132
