### ISSUE TITLE
pipeline sometimes fail on first run: 

### ISSUE THREAD

**Issue by erwangranger** [rh-aiservices-bu/insurance-claim-processing#143]
![image](https://github.com/rh-aiservices-bu/insurance-claim-processing/assets/32554862/1eecff26-d0ae-412d-b593-e189c2106de7)

this happens on the "response quality" check. 

happens to 5% of users, and passes on second try.

**Comment by RHRolun** [comment]
Same as #140

**Comment by guimou** [comment]
fixed by #148
