### ISSUE TITLE
Choose which version of RHOAI to use: RHOAI 2.7

### ISSUE THREAD

**Issue by erwangranger** [rh-aiservices-bu/insurance-claim-processing#160]
Which version to pick? 

currently at RHOAI 2.6. 

We want to test with RHOAI 2.7. 

RHOAI 2.8 would entail too many changes related to pipelines. 

also need the prereq: servicemesh / serverless.

**Comment by guimou** [comment]
PR opened with RHPDS team

**Comment by erwangranger** [comment]
done with 2.8
