### ISSUE TITLE
Attach process claims YAML in 5.5

### ISSUE THREAD

**Issue by cedricclyburn** [rh-aiservices-bu/insurance-claim-processing#166]
Hi folks, just wanted to make a documentation feature request for step 5.5 where we add in the YAML for the process claim as a pipeline import, I ended up going to GitHub to download the YAML then importing it, not sure if this is the intended action but I'll make a PR request with the direct link on the page if it helps. Thanks!

<img width="976" alt="image" src="https://github.com/rh-aiservices-bu/insurance-claim-processing/assets/54345140/5b8d78d3-bc11-47dc-af11-76246075323e">

**Comment by erwangranger** [comment]
I think this one was resolved. Thanks for the contribution!
