### ISSUE TITLE
Remove opencv-python from workbench image

### ISSUE THREAD

**Issue by guimou** [rh-aiservices-bu/insurance-claim-processing#196]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by rcarrata** [comment]
As a Workaround, in the Jupyter Lab Terminal:

```md
pip uninstall opencv-python
pip uninstall opencv-python-headless
pip install opencv-python-headless
```

Restart the Kernel and run all the cells and it works!
