### ISSUE TITLE
move pipeline into subfolder

### ISSUE THREAD

**Issue by erwangranger** [rh-aiservices-bu/insurance-claim-processing#39]
section 03 will have a lot of different files. 
can we move the current content of https://github.com/rh-aiservices-bu/insurance-claim-processing/tree/dev/lab-materials/03 into a subfolder called `07` to match the instructions numbering? (https://rh-aiservices-bu.github.io/insurance-claim-processing/modules/dev/03-07-sanity-check.html)

**Comment by RHRolun** [comment]
Completed with this PR: https://github.com/rh-aiservices-bu/insurance-claim-processing/pull/41
