### ISSUE TITLE
move pipeline image out of Robert's quay account. 

### ISSUE THREAD

**Issue by erwangranger** [rh-aiservices-bu/insurance-claim-processing#71]
we should copy this image out of @RHRolun 's quay account and into the aiservices account, and then update the instructions to use that instead. 

![image](https://github.com/rh-aiservices-bu/insurance-claim-processing/assets/32554862/f60710cb-0e5e-4d0d-9607-54bc188ddf86)

**Comment by erwangranger** [comment]
@RHRolun , pro-tip:  `podman pull` and `podman push` , even if it works, is not enough. 
You also need to make the new repos public because they create as private by default. 
I wish I knew that before also pull/pushing GBs back and forth.

**Comment by RHRolun** [comment]
@erwangranger Ah yea, I keep forgetting that they are private by default, have messed me up a few times...
